export const SAVE_NEW_MESSAGE = 'SAVE_NEW_MESSAGE';
export const FETCH_MESSAGES = 'FETCH_MESSAGES';
export const DELETE_MESSAGE = 'DELETE_MESSAGE';

export const LOAD_ALL_USERS = 'LOAD_ALL_USERS';

export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAILURE = 'REGISTER_USER_FAILURE';

export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';

export const LOGOUT_USER = 'LOGOUT_USER';

